import Head from "next/head";
import AboutSection from "../components/organisms/about-section";
import ExpertsSection from "../components/organisms/experts-section";
import HeroHeader from "../components/organisms/hero-header";
import ReviewsSection from "../components/organisms/reviews-section";
import ServicesSection from "../components/organisms/services-section";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroHeader />
      <AboutSection />
      <ServicesSection />
      <ExpertsSection />
      <ReviewsSection />
    </div>
  );
}
